### ISSUE TITLE
@jsquash/png fails to decode some images

### ISSUE THREAD

**Issue by CodeF53** [jamsinclair/jSquash#44]
**Describe the bug**
Given some `png`s, jsquash fails to decode and throws an error.

**To Reproduce**
1. Download [broken.zip](https://github.com/jamsinclair/jSquash/files/13801970/broken.zip) and unzip `broken.png` out of it
2. Load `broken.png`'s buffer
3. call `decode()` on `broken.png` buffer

[**Reproduction**](https://codesandbox.io/p/devbox/jsquash-faulty-png-decode-demo-v58zs3?file=%2Fsrc%2Findex.ts%3A6%2C27-6%2C33)
In this reproduction, there is 2 images, `working.png` and `broken.png`. The reproduction loads each image and attempts to decode it.

**Expected behavior**
```
decoding ./src/broken.png
    success!
```

**Actual behavior**
```
decoding ./src/broken.png
error: Uncaught (in promise) Error: `unwrap_throw` failed
    throw new Error(getStringFromWasm0(arg0, arg1));
          ^
    at imports.wbg.__wbindgen_throw (https://unpkg.com/@jsquash/png@2.2.0/codec/squoosh_png.js?module:157:11)
    at <anonymous> (https://unpkg.com/@jsquash/png@2.2.0/codec/squoosh_png_bg.wasm:1:91616)
    at <anonymous> (https://unpkg.com/@jsquash/png@2.2.0/codec/squoosh_png_bg.wasm:1:40587)
    at decode (https://unpkg.com/@jsquash/png@2.2.0/codec/squoosh_png.js?module:109:18)
    at decode (https://unpkg.com/@jsquash/png@2.2.0/decode.js?module:23:27)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async tryDecode (file:///workspace/src/index.ts:6:21)
    at async file:///workspace/src/index.ts:13:1
```

**Module Versions**
@jsquash/png 2.2.0 (latest)

**Additional Context**
I have no reason to believe the `broken.png` in question has problematic encoding, as it functions perfectly with the following:
1. Paint.NET
2. Windows Photo viewer
3. Discord's upload
4. Github's upload
5. Minecraft resource pack

**Comment by jamsinclair** [comment]
Thanks for the report @CodeF53. After playing around it seems like there might be an issue with the PNG decoding codec. Squoosh's implementation was quite basic and just repurposed the rust lib/png library.

When I find some time I'll see if I can find the exact error that is being reported in Rust and see if that helps us narrow it down. Alternatively, if you're running this code in the browser, you can likely utilize the Canvas API in the interim for a lightweight and faster png decoder to get the imagedata ([See MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData)).

**Comment by jamsinclair** [comment]
So the PNG itself is technically corrupted. It has an invalid ICC PROFILE checksum (Also reported by the tool https://www.nayuki.io/page/png-file-chunk-inspector). However, most systems seem to ignore this and still render the image.

The rust error is:
```
CRC error: expected 0x768af32e have 0x723989cd while decoding ChunkType { type: iCCP, critical: false, private: false, reserved: false, safecopy: false } chunk.
```

Oddly, this only happens in the Wasm build. When running the code via a rust binary it seems to be ok with the checksum issue 😅 . I'll need to make some time to comeback to this. In the interim, you could try use an image editor to resave the PNG correctly.

**Comment by CodeF53** [comment]
I kind of expected it would be something like that, but thought it shouldn't matter because so many other applications don't seem to care. 

I implemented a canvas based encode/decode fallback into my app for when this error occurs, but it is 10x slower than this library.

**Comment by CodeF53** [comment]
(Repost because github mobile app showed I sent it twice. So I tried deleting the duplicate, only to have both comments dissappear. Thanks github mobile!) 

I kind of expected it would be something like that, but thought it shouldn't matter because so many other applications don't seem to care. 

I implemented a canvas based encode/decode fallback into my app for when this error occurs, but it is 10x slower than this library.

**Comment by jamsinclair** [comment]
@CodeF53 I've released `@jsquash/png` version 3.0.0 which should now work with your broken pngs 👌

As it was going to require a major version release, I also included some other breaking changes. Please see the PR (#45) or [Changelog file](https://github.com/jamsinclair/jSquash/blob/main/packages/png/CHANGELOG.md) for details 🙇 .

Hope this helps with your app, happy new year! 🎉

**Comment by DeniDoman** [comment]
@jamsinclair could you please double check your fix? Because in the same example: [Reproduction](https://codesandbox.io/p/devbox/jsquash-faulty-png-decode-demo-v58zs3?file=%2Fsrc%2Findex.ts%3A6%2C27-6%2C33) - `broken.png` decoding is fixed, but `working.png` decoding now fails with the following error:

> error: Uncaught (in promise) IndexSizeError: Failed to construct 'ImageData': The input data length is not equal to (4 * width * height).

**Comment by jamsinclair** [comment]
Thanks for the report @DeniDoman. Not sure how this worked before... there now seems to be a bug with how we handle non-RGBA PNG files.

I'll have a fix ready shortly.

**Comment by DeniDoman** [comment]
Thank you very much @jamsinclair for the both: your project overall and the fast response. This application is extremely useful to optimize images online. 

Btw, I found one more problematic file, trying to decode it returns: `Error: Uncaught (in promise) Error: `unwrap_throw` failed`. So, could you please check the updated [Reproduction demo](https://codesandbox.io/p/devbox/jsquash-faulty-png-decode-demo-forked-8m8y6t) with the 3 files: `working.png`, `broken1.png` for the non-RGBA issue and `broken2.png` for the "unwrap_throw" error.

**Comment by jamsinclair** [comment]
@DeniDoman, thanks for the wait! I believe version 3.0.1 should now fix the issue 🙌 

Thanks for reporting the bug.

**Comment by DeniDoman** [comment]
Thank you for the fix, @jamsinclair ! And huge thank you for the project overall, you rock!

**Comment by MeFelixWang** [comment]
@jamsinclair thanks for this great project! I'm using `"@jsquash/png": "^3.0.1"`, but `Error: 'unwrap_throw' failed` still exists, any updates?

Here is the png file:

![king-vulture-8350517_640](https://github.com/jamsinclair/jSquash/assets/26833355/cbaae9d4-6457-486d-b9d4-7bcdd5bcaf8d)

**Comment by jamsinclair** [comment]
Thanks @MeFelixWang, that appears to be because the file is actually a jpeg and not a png. It has been given the wrong file extension.

Reading the file with the UNIX `file` command returns:
```
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, progressive, precision 8, 640x451, components 3
```

**Comment by jamsinclair** [comment]
I'll see if I can improve the error messaging 🤔

**Comment by MeFelixWang** [comment]
@jamsinclair thanks so much! I never thought about the extension. 😭

**Comment by jamsinclair** [comment]
@MeFelixWang No worries, easy mistake. Happens to all of us! Best of luck with your project.

**Comment by MeFelixWang** [comment]
@jamsinclair Cheers for all the mistakes we made before! 😆
